version: 2

sources:
  - name: raw
    database: ECOMMERCE_RT
    schema: RAW
    config:
      freshness:
        warn_after: {count: 30, period: minute}
        error_after: {count: 120, period: minute}
    tables:
      - name: RAW_ORDERS
        config:
          loaded_at_field: ingested_at
      - name: RAW_CLICKSTREAM
        config:
          loaded_at_field: ingested_at
      - name: RAW_CUSTOMERS_CDC
        config:
          loaded_at_field: ingested_at
      - name: RAW_PAYMENTS
        config:
          loaded_at_field: ingested_at
      - name: RAW_PARTNER_PRODUCTS
        config:
          loaded_at_field: ingested_at