USE DATABASE ECOMMERCE_RT;

-- ALLOWED_COUNTRIES is the source of truth for the row access policy.
-- Add rows here to extend access — no policy redeployment needed.
CREATE TABLE IF NOT EXISTS GOVERNANCE.ALLOWED_COUNTRIES (
  country_code STRING     NOT NULL,
  country_name STRING,
  region       STRING,
  is_active    BOOLEAN    NOT NULL DEFAULT TRUE,
  updated_at   TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_ALLOWED_COUNTRIES PRIMARY KEY (country_code) NOT ENFORCED
);

INSERT INTO GOVERNANCE.ALLOWED_COUNTRIES (country_code, country_name, region, is_active)
SELECT column1, column2, column3, column4
FROM VALUES
  ('US', 'United States',  'Americas', TRUE),
  ('CA', 'Canada',         'Americas', TRUE),
  ('GB', 'United Kingdom', 'Europe',   TRUE),
  ('DE', 'Germany',        'Europe',   TRUE),
  ('FR', 'France',         'Europe',   TRUE)
WHERE NOT EXISTS (SELECT 1 FROM GOVERNANCE.ALLOWED_COUNTRIES);

CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_CLASSIFICATION;
CREATE TAG IF NOT EXISTS GOVERNANCE.DATA_OWNER;
CREATE TAG IF NOT EXISTS GOVERNANCE.SLA_TIER;

ALTER TABLE SILVER.CUSTOMERS_SCD2 SET TAG GOVERNANCE.DATA_OWNER = 'hktodorova@gmail.com';
ALTER TABLE SILVER.CUSTOMERS_SCD2 MODIFY COLUMN email SET TAG GOVERNANCE.DATA_CLASSIFICATION = 'PII';
ALTER TABLE GOLD.DT_CUSTOMER_360 SET TAG GOVERNANCE.SLA_TIER = 'gold-30-minute';

CREATE OR REPLACE MASKING POLICY GOVERNANCE.MASK_EMAIL AS (val STRING) RETURNS STRING ->
  CASE
    WHEN CURRENT_ROLE() IN ('ROLE_DATA_PLATFORM_ADMIN', 'ROLE_DATA_ENGINEER') THEN val
    WHEN val IS NULL THEN NULL
    ELSE REGEXP_REPLACE(val, '(^.).*(@.*$)', '\\1***\\2')
  END;

ALTER TABLE SILVER.CUSTOMERS_SCD2 MODIFY COLUMN email SET MASKING POLICY GOVERNANCE.MASK_EMAIL;

CREATE OR REPLACE ROW ACCESS POLICY GOVERNANCE.COUNTRY_ACCESS_POLICY AS (country STRING) RETURNS BOOLEAN ->
  CURRENT_ROLE() IN ('ROLE_DATA_PLATFORM_ADMIN', 'ROLE_DATA_ENGINEER')
  OR EXISTS (
    SELECT 1
    FROM GOVERNANCE.ALLOWED_COUNTRIES ac
    WHERE ac.country_code = country
      AND ac.is_active = TRUE
  );

ALTER TABLE GOLD.DT_CUSTOMER_360 ADD ROW ACCESS POLICY GOVERNANCE.COUNTRY_ACCESS_POLICY ON (country);

CREATE SHARE IF NOT EXISTS SHARE_PARTNER_REVENUE;
GRANT USAGE ON DATABASE ECOMMERCE_RT TO SHARE SHARE_PARTNER_REVENUE;
GRANT USAGE ON SCHEMA ECOMMERCE_RT.GOLD TO SHARE SHARE_PARTNER_REVENUE;
GRANT SELECT ON DYNAMIC TABLE ECOMMERCE_RT.GOLD.DT_DAILY_REVENUE TO SHARE SHARE_PARTNER_REVENUE;

USE ROLE SECURITYADMIN;
GRANT USAGE ON SCHEMA ECOMMERCE_RT.GOLD TO ROLE ROLE_BI_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_RT.GOLD TO ROLE ROLE_BI_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA ECOMMERCE_RT.GOLD TO ROLE ROLE_BI_ANALYST;
GRANT USAGE ON SCHEMA ECOMMERCE_RT.FEATURES TO ROLE ROLE_DATA_SCIENTIST;
GRANT SELECT ON ALL TABLES IN SCHEMA ECOMMERCE_RT.FEATURES TO ROLE ROLE_DATA_SCIENTIST;

-- External partner: read-only access to shared revenue view via dedicated role.
GRANT USAGE ON DATABASE ECOMMERCE_RT TO ROLE ROLE_EXTERNAL_PARTNER;
GRANT USAGE ON SCHEMA ECOMMERCE_RT.GOLD TO ROLE ROLE_EXTERNAL_PARTNER;
GRANT SELECT ON DYNAMIC TABLE ECOMMERCE_RT.GOLD.DT_DAILY_REVENUE TO ROLE ROLE_EXTERNAL_PARTNER;
-- Row access policy on DT_CUSTOMER_360 already restricts data; partner sees allowed countries only.
GRANT SELECT ON DYNAMIC TABLE ECOMMERCE_RT.GOLD.DT_CUSTOMER_360 TO ROLE ROLE_EXTERNAL_PARTNER;
