-- 01_roles_warehouses_databases.sql
-- Run SECURITYADMIN block first (roles + grants), then switch to SYSADMIN for warehouses and DB objects.
-- Resource monitor is shared across all warehouses — adjust CREDIT_QUOTA to match your account limits.

USE ROLE SECURITYADMIN;

CREATE ROLE IF NOT EXISTS ROLE_DATA_PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS ROLE_DATA_ENGINEER;
CREATE ROLE IF NOT EXISTS ROLE_ANALYTICS_ENGINEER;
CREATE ROLE IF NOT EXISTS ROLE_BI_ANALYST;
CREATE ROLE IF NOT EXISTS ROLE_DATA_SCIENTIST;
CREATE ROLE IF NOT EXISTS ROLE_EXTERNAL_PARTNER;

GRANT ROLE ROLE_DATA_ENGINEER TO ROLE ROLE_DATA_PLATFORM_ADMIN;
GRANT ROLE ROLE_ANALYTICS_ENGINEER TO ROLE ROLE_DATA_PLATFORM_ADMIN;
GRANT ROLE ROLE_BI_ANALYST TO ROLE ROLE_ANALYTICS_ENGINEER;
GRANT ROLE ROLE_DATA_SCIENTIST TO ROLE ROLE_ANALYTICS_ENGINEER;

USE ROLE SYSADMIN;

CREATE DATABASE IF NOT EXISTS ECOMMERCE_RT;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.RAW;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.SILVER;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.GOLD;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.FEATURES;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.GOVERNANCE;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.OBSERVABILITY;
CREATE SCHEMA IF NOT EXISTS ECOMMERCE_RT.UTIL;

CREATE WAREHOUSE IF NOT EXISTS WH_INGEST_XS
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Batch and streaming ingestion workloads';

CREATE WAREHOUSE IF NOT EXISTS WH_TRANSFORM_M
  WAREHOUSE_SIZE = MEDIUM
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 3
  SCALING_POLICY = ECONOMY
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'ELT, dbt, streams/tasks and dynamic table refreshes';

CREATE WAREHOUSE IF NOT EXISTS WH_ANALYTICS_S
  WAREHOUSE_SIZE = SMALL
  MIN_CLUSTER_COUNT = 1
  MAX_CLUSTER_COUNT = 4
  SCALING_POLICY = STANDARD
  AUTO_SUSPEND = 90
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'BI and ad-hoc analytics';

CREATE WAREHOUSE IF NOT EXISTS WH_ML_M
  WAREHOUSE_SIZE = MEDIUM
  AUTO_SUSPEND = 180
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Snowpark feature engineering and ML workloads';

CREATE RESOURCE MONITOR IF NOT EXISTS RM_ECOMMERCE_MONTHLY
  WITH CREDIT_QUOTA = 500
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 70 PERCENT DO NOTIFY
    ON 90 PERCENT DO NOTIFY
    ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE WH_INGEST_XS SET RESOURCE_MONITOR = RM_ECOMMERCE_MONTHLY;
ALTER WAREHOUSE WH_TRANSFORM_M SET RESOURCE_MONITOR = RM_ECOMMERCE_MONTHLY;
ALTER WAREHOUSE WH_ANALYTICS_S SET RESOURCE_MONITOR = RM_ECOMMERCE_MONTHLY;
ALTER WAREHOUSE WH_ML_M SET RESOURCE_MONITOR = RM_ECOMMERCE_MONTHLY;

USE ROLE SECURITYADMIN;
GRANT USAGE ON DATABASE ECOMMERCE_RT TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON DATABASE ECOMMERCE_RT TO ROLE ROLE_ANALYTICS_ENGINEER;
GRANT USAGE ON DATABASE ECOMMERCE_RT TO ROLE ROLE_BI_ANALYST;
GRANT USAGE ON DATABASE ECOMMERCE_RT TO ROLE ROLE_DATA_SCIENTIST;

GRANT USAGE ON WAREHOUSE WH_INGEST_XS TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM_M TO ROLE ROLE_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_TRANSFORM_M TO ROLE ROLE_ANALYTICS_ENGINEER;
GRANT USAGE ON WAREHOUSE WH_ANALYTICS_S TO ROLE ROLE_BI_ANALYST;
GRANT USAGE ON WAREHOUSE WH_ML_M TO ROLE ROLE_DATA_SCIENTIST;
