USE ROLE SYSADMIN;
USE DATABASE ECOMMERCE_RT;

CREATE FILE FORMAT IF NOT EXISTS UTIL.FF_JSON
  TYPE = JSON
  STRIP_OUTER_ARRAY = TRUE
  IGNORE_UTF8_ERRORS = TRUE;

CREATE FILE FORMAT IF NOT EXISTS UTIL.FF_CSV
  TYPE = CSV
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  SKIP_HEADER = 1
  NULL_IF = ('', 'NULL', 'null')
  ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE STAGE IF NOT EXISTS RAW.STG_ORDERS_JSON
  FILE_FORMAT = UTIL.FF_JSON
  COMMENT = 'Internal stage for Orders API JSON files';

CREATE STAGE IF NOT EXISTS RAW.STG_PARTNER_CSV
  FILE_FORMAT = UTIL.FF_CSV
  COMMENT = 'Internal stage for partner batch CSV files';

CREATE STAGE IF NOT EXISTS RAW.STG_CLICKSTREAM_JSON
  FILE_FORMAT = UTIL.FF_JSON
  COMMENT = 'Internal stage for clickstream JSON replay files';
